### DISCUSSION TITLE
[nx-docker] How to use extracted metadata in cache-from configurations

### DISCUSSION THREAD

**Discussion by roderik** [gperdomor/oss#328] [Q&A] [answered]
I'm trying to recreate my build flow using bare buildx on github actions using this plugin but I've got some issues setting up the buildx caching.

Given the following config:
```
        "docker": {
          "executor": "@nx-tools/nx-docker:build",
          "options": {
            "file": "apps/api/Dockerfile",
            "tags": ["ghcr.io/settlemint/bpaas-console-api:dev"],
            "meta": {
              "enabled": true,
              "images": ["ghcr.io/settlemint/bpaas-console-api"],
              "tags": [
                "type=schedule",
                "type=ref,event=branch",
                "type=ref,event=tag",
                "type=ref,event=pr",
                "type=sha,format=long,prefix="
              ]
            }
          }
        },
```

The container gets build and tagged with the long SHA and a slug of my branch name

![CleanShot 2021-07-30 at 07 47 11](https://user-images.githubusercontent.com/16780/127606721-fcebceed-f453-4ffa-a9bc-485c3750532a.png)

Good so far.

But some of these build steps do not change, and are very heavy, so I'm used to using cache-from with the branch name slug so these expensive layers only get build once per branch.

```
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Build and push Launchpad Cluster Manager (Not Production)
        uses: docker/build-push-action@v2
        with:
          context: ./packages/launchpad-nest/
          file: ./packages/launchpad-nest/cluster-manager.Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=ghcr.io/settlemint/launchpad-nest-cluster-manager:${{ env.GITHUB_REF_SLUG }}
          cache-to: type=inline
          tags: |
            ghcr.io/settlemint/launchpad-nest-cluster-manager:${{ env.GITHUB_REF_SLUG }}
            ghcr.io/settlemint/launchpad-nest-cluster-manager:${{ env.GITHUB_REF_SLUG }}-build${{ github.run_number }}
```

The challenge now with nx-docker is, how do i use the auto extracted metadata, in the cache-from config.
