### DISCUSSION TITLE
Getting missing github token for the workflow when using NX container build

### DISCUSSION THREAD

**Discussion by ashventech** [gperdomor/oss#784] [Q&A]
I am trying to build a container using Nx container and upload it to azure container registry. It does not work as it cant seem to get the github token from the context. Not sure what am I missing.  Would really appreciate and help or pointers. Here is my github actions workflow :

```
name: Create and Upload docker images to ACR
permissions: write-all
on:
  push:
    tags: ['v*.*.*']

env:
  SERVICE_IMAGE_NAME: test-service

jobs:
  publish-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: yarn install --immutable --immutable-cache --check-cache
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: npx nx container auth-service
```

I get the following error :
```Nx Container  Removing temp folder /tmp/docker-build-push-nc3RX5
 >  NX   Missing github token
Error: Missing github token
    at repo4 (/home/runner/work/***/***/node_modules/@nx-tools/ci-context/index.cjs:123:11)
    at RepoProxyFactory.create (/home/runner/work/***/***/node_modules/@nx-tools/ci-context/index.cjs:273:14)
    at getMetadata (/home/runner/work/***/***/node_modules/@nx-tools/container-metadata/index.cjs:878:57)
    at async run (/home/runner/work/***/***/node_modules/@nx-tools/nx-container/src/executors/build/executor.js:44:26) ```
